version: '3.8'

networks:
  net:
    driver: bridge

volumes:
  postgres-data:

services:
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      net:
    restart: unless-stopped
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
  graphile:
    build:
      context: ./graphile/
      dockerfile: Dockerfile
      # target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./schema/:/tmp/schema/
      - ./graphile/:/data/postgraphile/
    depends_on:
      - db
    networks:
      net:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      # target: dev
    volumes:
      - ./backend/:/app/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      net:
    restart: unless-stopped

