# Generated by Django 5.0a1 on 2023-10-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='PointOfInterest',
        ),
        migrations.AddField(
            model_name='route',
            name='points',
            field=models.ManyToManyField(to='routes.pointofinterest'),
        ),
    ]
