# Generated by Django 5.0a1 on 2023-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_point_pointofinterest_route_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
