# Generated by Django 5.0a1 on 2023-10-14 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_rename_owner_route_user'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='route',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('team__isnull', False), _connector='OR'), name='always_linked', violation_error_message='Route must always be linked to either team or user'),
        ),
    ]
