# Generated by Django 5.0b1 on 2023-11-19 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_route_team_alter_route_user_route_always_linked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
